import Head from "next/head";
import styles from "../styles/Home.module.css";
//import Image from "next/image";
import dynamic from "next/dynamic";
import Layout from "/component/layouts/Layout";
const HomeOverview1 = dynamic(
  () => import("/component/home/overview/homeOverview1/HomeOverview1.js"),
  {
    loading: () => <p>Loading...</p>,
  }
);
const HomeOverview2 = dynamic(
  () => import("/component/home/overview/homeOverview2/HomeOverview2.js"),
  {
    loading: () => <p>Loading...</p>,
  }
);
const HomeOverview3 = dynamic(
  () => import("/component/home/overview/homeOverview3/HomeOverview3.js"),
  {
    loading: () => <p>Loading...</p>,
  }
);
const Slider = dynamic(() => import("/component/home/slider/Slider.js"), {
  loading: () => <p>Loading...</p>,
});
const Company = dynamic(() => import("/component/home/company/Company.js"), {
  loading: () => <p>Loading...</p>,
});
const Importance = dynamic(
  () => import("/component/home/importance/Importance.js"),
  {
    loading: () => <p>Loading...</p>,
  }
);
const WorkPlatforms = dynamic(
  () => import("/component/home/workPlatforms/WorkPlatforms.js"),
  {
    loading: () => <p>Loading...</p>,
  }
);
const Studio = dynamic(() => import("/component/home/studio/Studio.js"), {
  loading: () => <p>Loading...</p>,
});
const Testimonial = dynamic(
  () => import("/component/home/testimonial/Testimonial.js"),
  {
    loading: () => <p>Loading...</p>,
  }
);
const WorkShowcase = dynamic(
  () => import("/component/home/workshowcase/WorkShowcase.js"),
  {
    loading: () => <p>Loading...</p>,
  }
);
//import Slider from "../component/home/slider/Slider";
//import Company from "../component/home/company/Company";
//import Importance from "../component/home/importance/importance";
// import HomeOverview1 from "../component/home/overview/homeOverview1/HomeOverview1";
// import HomeOverview2 from "../component/home/overview/homeOverview2/HomeOverview2";
// import HomeOverview3 from "../component/home/overview/homeOverview3/HomeOverview3";
//import WorkPlatforms from "../component/home/workPlatforms/WorkPlatforms";
//import Studio from "../component/home/studio/Studio";
//import Testimonial from "../component/home/testimonial/Testimonial";
//import WorkShowcase from "../component/home/workshowcase/WorkShowcase";

export default function Home() {
  return (
    <>
      <Head>
        <title>Influencer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"
          integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm"
          crossOrigin="anonymous"
        ></link>
      </Head>

      <Layout>
        <Slider />
        <Company />
        <Importance />
        <HomeOverview1 />
        <HomeOverview2 />
        <HomeOverview3 />
        <WorkPlatforms />
        <Studio />
        <Testimonial />
        <WorkShowcase />
      </Layout>
    </>
  );
}
